### ISSUE TITLE
Make this program work for portable DC also

### ISSUE THREAD

**Issue by ags1234** [t0mmili/dc-themer#3]
![2024-07-31_180402](https://github.com/user-attachments/assets/ddfb2fc4-544b-4ec2-bdd8-1489b9386f29)

I am using a portable version of DC, so there are no files in the standard path.

After searching for files and not finding them in AppData\Roaming\doublecmd, offer the user the possibility to manually set the path.
Make this possible with a Browse button, of by dragging needed files on your form.

**Comment by t0mmili** [comment]
@ags1234 Thanks for trying out DC Themer! I'm aware of this issue. Since development just started I will try to add features gradually. All ideas for enhancements are stored in [TODO.md](https://github.com/t0mmili/dc-themer/blob/main/TODO.md).
Now, going back to configs default path. Currently, the only way to change DC Themer configuration is to edit [config.py](https://github.com/t0mmili/dc-themer/blob/main/app/config.py) and compile exe on your own. Binary attached to release is holding default config from main branch.
Anyway, I will leave this issue open until I'll start working on user-editable config.

**Comment by t0mmili** [comment]
@ags1234 Please check [the new release v0.3.0](https://github.com/t0mmili/dc-themer/releases/tag/v0.3.0). It adds user config in json. Manually edited for now, but it's just a starting point 😉

**Comment by ags1234** [comment]
I ckecked version 0.3.0.
It works for custom DC config paths.
Thanks for the adaptation.

**Comment by ags1234** [comment]
Are you interested in additional theme suggestions?

**Comment by t0mmili** [comment]
> Are you interested in additional theme suggestions?

If it's related to scheme and elements that should be included then of course - feel free to open new issue.
